Repository dnd-side-project/dnd-9th-8-backend, pull requests merged in 2023-08, with the labels that each got.

#2 Spring Boot 프로젝트 생성
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/site/packit/packit/PackItApplication.java
  src/main/resources/application.properties
  src/test/java/site/packit/packit/PackItApplicationTests.java
Labels: setting

#4 Feature/#3 global dev
  .gitignore
  build.gradle
  src/main/java/site/packit/packit/global/audit/AuditConfig.java
  src/main/java/site/packit/packit/global/audit/BaseEntity.java
  src/main/java/site/packit/packit/global/audit/BaseTimeEntity.java
  src/main/java/site/packit/packit/global/exception/ErrorCode.java
  src/main/java/site/packit/packit/global/exception/GlobalErrorCode.java
  src/main/java/site/packit/packit/global/exception/GlobalExceptionHandler.java
  src/main/java/site/packit/packit/global/exception/ResourceNotFoundException.java
  src/main/java/site/packit/packit/global/response/error/ErrorApiResponse.java
  src/main/java/site/packit/packit/global/response/success/MultipleSuccessApiResponse.java
  src/main/java/site/packit/packit/global/response/success/SingleSuccessApiResponse.java
  src/main/java/site/packit/packit/global/response/success/SuccessApiResponse.java
  src/main/java/site/packit/packit/global/util/GsonUtil.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feat, setting

#6 회원 인증 기본 기능 개발
  .gitignore
  build.gradle
  src/main/java/site/packit/packit/domain/auth/constant/AuthenticationProvider.java
  src/main/java/site/packit/packit/domain/auth/controller/AuthController.java
  src/main/java/site/packit/packit/domain/auth/dto/ReissueTokenResponse.java
  src/main/java/site/packit/packit/domain/auth/exception/AuthErrorCode.java
  src/main/java/site/packit/packit/domain/auth/exception/AuthExceptionHandler.java
  src/main/java/site/packit/packit/domain/auth/exception/CustomAuthenticationEntryPoint.java
  src/main/java/site/packit/packit/domain/auth/exception/InvalidAuthenticationProviderException.java
  src/main/java/site/packit/packit/domain/auth/exception/OAuth2ProviderMisMatchException.java
  src/main/java/site/packit/packit/domain/auth/exception/TokenException.java
  src/main/java/site/packit/packit/domain/auth/filter/TokenAuthenticationFilter.java
  src/main/java/site/packit/packit/domain/auth/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/site/packit/packit/domain/auth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/site/packit/packit/domain/auth/handler/TokenAccessDeniedHandler.java
  src/main/java/site/packit/packit/domain/auth/info/CustomUserPrincipal.java
  src/main/java/site/packit/packit/domain/auth/info/oauth2/KakaoOAuth2UserInfo.java
  src/main/java/site/packit/packit/domain/auth/info/oauth2/NaverOAuth2UserInfo.java
  src/main/java/site/packit/packit/domain/auth/info/oauth2/OAuth2UserInfo.java
  src/main/java/site/packit/packit/domain/auth/info/oauth2/OAuth2UserInfoFactory.java
  src/main/java/site/packit/packit/domain/auth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/site/packit/packit/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/site/packit/packit/domain/auth/service/AuthService.java
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/auth/token/AuthToken.java
  src/main/java/site/packit/packit/domain/auth/token/AuthTokenProvider.java
  src/main/java/site/packit/packit/domain/auth/token/RefreshToken.java
  src/main/java/site/packit/packit/domain/member/constant/MemberRole.java
  src/main/java/site/packit/packit/domain/member/constant/MemberStatus.java
  src/main/java/site/packit/packit/domain/member/dto/CreateMemberDto.java
  src/main/java/site/packit/packit/domain/member/entity/Member.java
  src/main/java/site/packit/packit/domain/member/exception/InvalidRedirectUriException.java
  src/main/java/site/packit/packit/domain/member/exception/MemberErrorCode.java
  src/main/java/site/packit/packit/domain/member/repository/MemberRepository.java
  src/main/java/site/packit/packit/domain/member/service/MemberService.java
  src/main/java/site/packit/packit/domain/member/service/MemberServiceImpl.java
  src/main/java/site/packit/packit/global/exception/ResourceNotFoundException.java
  src/main/java/site/packit/packit/global/security/config/JwtConfig.java
  src/main/java/site/packit/packit/global/security/config/OAuth2Config.java
  src/main/java/site/packit/packit/global/security/config/SecurityConfig.java
  src/main/java/site/packit/packit/global/util/CookieUtil.java
  src/main/java/site/packit/packit/global/util/HeaderUtil.java
  src/main/resources/application.yml
Labels: feat

#8 MariaDB-Driver 적용
  .gitignore
  build.gradle
  src/main/java/site/packit/packit/global/security/config/SecurityConfig.java
Labels: setting

#12 feat: #10 Travel Entity Class 생성
  src/main/java/site/packit/packit/domain/travel/constant/DestinationType.java
  src/main/java/site/packit/packit/domain/travel/constant/TravelStatus.java
  src/main/java/site/packit/packit/domain/travel/entity/Travel.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#13 feat: 여행 도메인 기본 API 개발
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/CreateTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/dto/UpdateTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/entity/Travel.java
  src/main/java/site/packit/packit/domain/travel/exception/TravelErrorCode.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#15 회원 도메인 API & Image 업로드 API 구현
  build.gradle
  src/main/java/site/packit/packit/domain/auth/info/CustomUserPrincipal.java
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/image/controller/ImageController.java
  src/main/java/site/packit/packit/domain/image/dto/api/UploadImageResponse.java
  src/main/java/site/packit/packit/domain/image/service/AmazonS3ImageService.java
  src/main/java/site/packit/packit/domain/image/service/ImageService.java
  src/main/java/site/packit/packit/domain/member/controller/MemberController.java
  src/main/java/site/packit/packit/domain/member/dto/MemberDto.java
  src/main/java/site/packit/packit/domain/member/entity/Member.java
  src/main/java/site/packit/packit/domain/member/service/MemberService.java
  src/main/java/site/packit/packit/domain/member/service/MemberServiceImpl.java
  src/main/java/site/packit/packit/global/audit/AuditConfig.java
  src/main/java/site/packit/packit/global/audit/AuditorAwareImpl.java
  src/main/java/site/packit/packit/global/aws/s3/S3Config.java
Labels: feat, setting

#16 feat: 체크리스트 기본 API 개발
  src/main/java/site/packit/packit/domain/checkList/controller/CheckListController.java
  src/main/java/site/packit/packit/domain/checkList/dto/CreateCheckListRequest.java
  src/main/java/site/packit/packit/domain/checkList/dto/UpdateCheckListRequest.java
  src/main/java/site/packit/packit/domain/checkList/entity/CheckList.java
  src/main/java/site/packit/packit/domain/checkList/excepiton/CheckListErrorCode.java
  src/main/java/site/packit/packit/domain/checkList/repository/CheckListRepository.java
  src/main/java/site/packit/packit/domain/checkList/service/CheckListService.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#19 fix: 여행/체크리스트 삭제 시 하위 항목도 삭제
  src/main/java/site/packit/packit/domain/checkList/service/CheckListService.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#21 문제점 해결
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/image/service/AmazonS3ImageService.java
  src/main/java/site/packit/packit/domain/image/service/ImageService.java
  src/main/java/site/packit/packit/domain/member/controller/MemberController.java
  src/main/java/site/packit/packit/domain/member/dto/ChangeNicknameRequest.java
  src/main/java/site/packit/packit/domain/member/dto/ChangeProfileImageRequest.java
  src/main/java/site/packit/packit/domain/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: bug

#24 feat: 여행 도메인 조회 API 개발
  src/main/java/site/packit/packit/domain/checkList/repository/CheckListRepository.java
  src/main/java/site/packit/packit/domain/item/repository/ItemRepository.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/CheckListDto.java
  src/main/java/site/packit/packit/domain/travel/dto/GetTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/dto/ItemDto.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelDetailDto.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelListDto.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#25 fix : 여행 엔티티에서 TravelStatus 삭제
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/entity/Travel.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: refactor

#29 feat: 보관함 관련 기능 개발
  src/main/java/site/packit/packit/domain/storage/controller/StorageController.java
  src/main/java/site/packit/packit/domain/storage/dto/StorageListDto.java
  src/main/java/site/packit/packit/domain/storage/dto/UpdateStorage.java
  src/main/java/site/packit/packit/domain/storage/entity/Storage.java
  src/main/java/site/packit/packit/domain/storage/repository/StorageRepository.java
  src/main/java/site/packit/packit/domain/storage/service/StorageService.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelDetailDto.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelListDto.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#31 fix : 저장함 관련 memberId RequestBody로 받게 수정
  src/main/java/site/packit/packit/domain/storage/controller/StorageController.java
Labels: refactor

#32 S3 이미지 경로 분리 적용 및 기본 이미지 & 이름 사용하도록 적용
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/image/service/AmazonS3ImageService.java
Labels: refactor

#35 fix: RequestParam으로 수정
  src/main/java/site/packit/packit/domain/storage/controller/StorageController.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: refactor

#36 feat : 기존 템플릿 이용 여행 생성 API
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/BringTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#37 프론트 요구사항 반영
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/member/controller/MemberController.java
  src/main/java/site/packit/packit/domain/member/dto/CreateMemberDto.java
  src/main/java/site/packit/packit/domain/member/dto/MemberWithTravelCountDto.java
  src/main/java/site/packit/packit/domain/member/entity/Member.java
  src/main/java/site/packit/packit/domain/travel/dto/BringTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
  src/main/java/site/packit/packit/global/web/WebConfig.java
Labels: refactor

#40 fix : 여행 관련 memberId 받는 방식 변경
  src/main/java/site/packit/packit/domain/storage/controller/StorageController.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/BringTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/dto/CreateTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/exception/TravelErrorCode.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: refactor

#42 fix : 여행 삭제 API 오류 수정
  src/main/java/site/packit/packit/domain/storage/repository/StorageRepository.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: bug

#46 fix: 예외처리 추가
  src/main/java/site/packit/packit/domain/checkList/controller/CheckListController.java
  src/main/java/site/packit/packit/domain/checkList/excepiton/CheckListErrorCode.java
  src/main/java/site/packit/packit/domain/checkList/service/CheckListService.java
  src/main/java/site/packit/packit/domain/item/controller/ItemController.java
  src/main/java/site/packit/packit/domain/item/exception/ItemErrorCode.java
  src/main/java/site/packit/packit/domain/item/service/ItemService.java
Labels: refactor

#47 fix : CheckList 엔티티에 필수 여부 추가
  src/main/java/site/packit/packit/domain/checkList/entity/CheckList.java
  src/main/java/site/packit/packit/domain/checkList/service/CheckListService.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/CheckListDto.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: refactor

#49 feat: 수정 관련 API 추가
  src/main/java/site/packit/packit/domain/checkList/controller/CheckListController.java
  src/main/java/site/packit/packit/domain/checkList/dto/UpdateListTitleRequest.java
  src/main/java/site/packit/packit/domain/checkList/entity/CheckList.java
  src/main/java/site/packit/packit/domain/checkList/service/CheckListService.java
  src/main/java/site/packit/packit/domain/item/controller/ItemController.java
  src/main/java/site/packit/packit/domain/item/dto/UpdateItemTitleRequest.java
  src/main/java/site/packit/packit/domain/item/entity/Item.java
  src/main/java/site/packit/packit/domain/item/service/ItemService.java
Labels: feat

#50 fix : 여행 상세 조회에 id 추가
  src/main/java/site/packit/packit/domain/travel/dto/TravelDetailDto.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: refactor

#51 프로필 이미지 변경 API 입력 타입 변경
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/member/controller/MemberController.java
  src/main/java/site/packit/packit/domain/member/dto/UpdateMemberRequest.java
Labels: feat, refactor

#52 로그인 리다이렉트 URL 회원 가입 최초 유무 파라미터 추가
  src/main/java/site/packit/packit/domain/auth/constant/LoginMemberStatus.java
  src/main/java/site/packit/packit/domain/auth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
Labels: feat

#53 회원 이메일 인증 기능 구현
  .gitignore
  build.gradle
  src/main/java/site/packit/packit/domain/auth/email/EmailAuthenticationCode.java
  src/main/java/site/packit/packit/domain/auth/email/EmailAuthenticationCodeRepository.java
  src/main/java/site/packit/packit/domain/auth/email/EmailAuthenticationRequest.java
  src/main/java/site/packit/packit/domain/auth/email/EmailConfig.java
  src/main/java/site/packit/packit/domain/auth/email/controller/EmailController.java
  src/main/java/site/packit/packit/domain/auth/email/exception/EmailAuthenticationException.java
  src/main/java/site/packit/packit/domain/auth/email/exception/EmailErrorCode.java
  src/main/java/site/packit/packit/domain/auth/email/exception/EmailExceptionHandler.java
  src/main/java/site/packit/packit/domain/auth/email/service/EmailService.java
  src/main/java/site/packit/packit/domain/auth/email/service/EmailServiceImpl.java
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/member/dto/MemberDto.java
  src/main/java/site/packit/packit/domain/member/dto/MemberWithTravelCountDto.java
  src/main/java/site/packit/packit/domain/member/entity/Member.java
  src/main/java/site/packit/packit/global/security/config/SecurityConfig.java
Labels: feat, refactor, setting

#55 LB 상태 체크용 API 추가
  src/main/java/site/packit/packit/global/lbcheck/CheckController.java
  src/main/java/site/packit/packit/global/security/config/SecurityConfig.java
Labels: setting

#57 [Fix] 프론트엔드 배포 URL 설정 추가
  src/main/java/site/packit/packit/global/filter/CorsFilter.java
  src/main/java/site/packit/packit/global/web/WebConfig.java
Labels: bug

#59 이메일 인증 리팩토링
  src/main/java/site/packit/packit/domain/auth/email/EmailAuthenticationRequest.java
  src/main/java/site/packit/packit/domain/auth/email/controller/EmailController.java
  src/main/java/site/packit/packit/domain/auth/email/service/EmailService.java
  src/main/java/site/packit/packit/domain/auth/email/service/EmailServiceImpl.java
  src/main/java/site/packit/packit/domain/member/entity/Member.java
Labels: refactor

#61 [Fix] 이메일 인증 에러 조치
  src/main/java/site/packit/packit/domain/auth/dto/EmailAuthenticationCodeRequest.java
  src/main/java/site/packit/packit/domain/auth/email/controller/EmailController.java
Labels: bug

#63 feat : 기본 체크리스트 템플릿 추가
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#65 S3 이전에 따른 URL 변경
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
Labels: refactor

#67 이메일 인증 링크 변경 및 인증 시간 변경
  src/main/java/site/packit/packit/domain/auth/email/service/EmailServiceImpl.java
  src/main/java/site/packit/packit/global/security/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: refactor

#68 fix : 여행 생성 api 오류 수정
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
Labels: bug

#70 fix : 지난 여행 조회시 d-day 날짜 넘어간 여행 추가
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: bug

#71 여행 하루 전 이메일 알림 기능 구현
  src/main/java/site/packit/packit/PackItApplication.java
  src/main/java/site/packit/packit/domain/auth/email/controller/EmailController.java
  src/main/java/site/packit/packit/domain/auth/email/service/EmailAuthenticationService.java
  src/main/java/site/packit/packit/domain/auth/email/service/EmailAuthenticationServiceImpl.java
  src/main/java/site/packit/packit/domain/email/dto/SendEmailDto.java
  src/main/java/site/packit/packit/domain/email/service/EmailService.java
  src/main/java/site/packit/packit/domain/email/service/EmailServiceImpl.java
  src/main/java/site/packit/packit/domain/notification/service/TravelNotificationService.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
Labels: feat

#73 fix : 보관함 추가 시 본인만 가능하게
  src/main/java/site/packit/packit/domain/storage/service/StorageService.java
Labels: bug
